catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^product/(?P<pk>[0-9]+)/$', views.CatalogView.as_view(page='product'), name='product'),
    url(r'^catalog$', views.CatalogView.as_view(page='catalog'), name='catalog'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CatalogView.as_view(page='category'), name='category'),
    url(r'^order/$', views.OrderView.as_view(), name='order_path'),
]

okinava/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from okinava import settings
from catalog.views import MainView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view(), name='main'),
    url(r'', include('catalog.urls', namespace="catalog")),
    url(r'', include('pages.urls', namespace="pages")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^delivery$', views.PageView.as_view(page='delivery'), name='delivery_page'),
    url(r'^contacts$', views.PageView.as_view(page='contacts'), name='contact_page'),
]

catalog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib import admin
from django.utils import timezone


class Category(models.Model):
    ctg_name = models.CharField(max_length=250, verbose_name=u'Название категории')
    ctg_image = models.ImageField(upload_to='images', blank=True, verbose_name=u'Изображение категории')
    ctg_slug = models.SlugField(max_length=250, verbose_name=u'URL-ссылка',help_text=u'Сокращенный заголовок латиницей, используется для создания человекопонятного URL, должен быть уникальным')
    ctg_show = models.BooleanField(default=False, verbose_name=u'Показывать на сайте')
    ctg_sort = models.IntegerField(default=0, verbose_name=u'Сортировка')

    def __unicode__(self):
        return self.ctg_name

    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'


class Product(models.Model):
    prod_name = models.CharField(max_length=250, verbose_name=u'Наименование товара')
    prod_categ = models.ForeignKey(Category, verbose_name=u'Категория товара', null=True, blank=True)
    prod_image = models.ImageField(upload_to='images', blank=True, verbose_name=u'Изображение товара')
    prod_price = models.IntegerField(default=0, verbose_name=u'Цена (руб.)')
    prod_oldprice = models.IntegerField(default=0, verbose_name=u'Старая цена (руб.)')
    prod_weight = models.PositiveIntegerField(default=0, verbose_name=u'Вес (грамм)')
    prod_isnovelty = models.BooleanField(default=False, verbose_name=u'Новинка')
    prod_ishit = models.BooleanField(default=False, verbose_name=u'Хит')
    prod_show = models.BooleanField(default=False, verbose_name=u'Показывать на сайте')
    prod_descr = RichTextUploadingField(blank=True, default='')

    def __unicode__(self):
        return self.prod_name

    class Meta:
        verbose_name = u'Товар'
        verbose_name_plural = u'Товары'


class Order(models.Model):
    order_date = models.DateTimeField(default=timezone.now)
    order_product = models.ForeignKey(Product)
    person_name = models.CharField(max_length=250)
    person_phone = models.CharField(max_length=250)
    is_new = models.BooleanField(default=True)
    message = models.TextField(null=True, blank=True)

    def makeorder(self):
        self.save()

    def __unicode__(self):
        return self.order_date.strftime('%c')

pages/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

catalog/forms.py
from . models import Product, Order
from django import forms


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('person_name', 'person_phone', 'message', 'order_product')

catalog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Order
from django.db.models import Q
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from .forms import OrderForm
from django.http import HttpResponseRedirect


class BaseView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['full_menu'] = Category.objects.filter(ctg_show=1)
        return context


class CatalogView(BaseView):
    page = None

    def get_context_data(self, **kwargs):
        context = super(CatalogView, self).get_context_data(**kwargs)
        context['order_form'] = OrderForm
        if self.page == 'product':
            self.template_name = 'catalog/product-detail.html'
            context['prodInfo'] = get_object_or_404(Product, pk=kwargs.get('pk'))
        elif self.page == 'category':
            self.template_name = 'catalog/catalog-list.html'
            category = get_object_or_404(Category, pk=kwargs.get('pk'))
            context['ctlgItems'] = Product.objects.filter(prod_show=1, prod_categ_id=kwargs.get('pk'))
        elif self.page == 'catalog':
            self.template_name = 'catalog/full-menu.html'
        return context


class MainView(BaseView):
    template_name = 'catalog/catalog-hits.html'

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['ctlgItems'] = Product.objects.filter(prod_show=1).filter(Q(prod_ishit=1) | Q(prod_isnovelty=1))
        return context


class OrderView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'catalog/catalog-list.html'

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

pages/views.py
from django.shortcuts import render
from catalog.views import BaseView

# def delivery_page(request):
#     return render(request, 'pages/delivery.html')
#
# def contacts_page(request):
#     return render(request, 'pages/contacts.html')


class PageView(BaseView):
    page = None
    def get_context_data(self, **kwargs):
        context = super(PageView, self).get_context_data(**kwargs)
        if self.page == 'delivery':
            self.template_name = 'pages/delivery.html'
        elif self.page == 'contacts':
            self.template_name = 'pages/contacts.html'
        return context

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>Японская кухня Окинава</title>
	    <meta name="description" content="Японская кухня Окинава"/>
	    <meta name="keywords" content="Японская кухня Окинава"/>
	    <!-- Stylesheets -->
	    <link rel="stylesheet" href="{% static 'css/style.css' %}">
         <link rel="stylesheet" href="{% static 'css/others.css' %}">
	    <link rel="icon" type="image/x-icon" href="img/favicon.ico">
	</head>

    <body>
        {% include "blocks/header.html" %}
		{% include "blocks/nav.html" %}


		{% block content %}
		{% endblock %}

		<!-- {% include "blocks/presents.html" %} -->

		{% include "blocks/footer.html" %}
	</body>
</html>

templates/blocks/footer.html
{% load staticfiles %}

<footer>
    <div class="large-wrapper clr">
        <p class="greeting">Ждем вас в нашем кафе Окинава в Пскове!</p>
        <div class="ftr-col-contacts">
            <div class="indents clr">
                <ul class="ftr-contacts">
                    <li class="address">г. Псков, ул. Михайловская, 1</li>
                    <li class="phone">
                        <a href="tel:+78112600601">8 (8112) 600-601</a>
                        <a href="tel:+79118896060">8-911-889-60-60</a>
                    </li>
                    <li class="time">Ежедневно: <br> 11:00 - 23:00, пт-сб: до 1:00 </li>
                    <li class="sticks">Заказ столиков: <a href="tel:+78112600601">8 (8112) 600-601</a> </li>
                </ul>
                <ul class="ftr-contacts">
                    <li class="address">ул. Льва Толстого, 3</li>
                    <li class="phone">
                        <a href="tel:+79118996060">8-911-899-60-60</a>
                        <a href="tel:+78112201060">8 (8112) 20-10-60</a>
                    </li>
                    <li class="time">Ежедневно: <br> 10:00 - 23:00 </li>
                    <li class="sticks">Заказ столиков: <a href="tel:+79118996060">8-911-899-60-60</a> </li>
                </ul>
            </div>
            <div class="ftr-soc">
                <span>Окинава в социальных сетях:</span>
                <div class="soc-list">
                    <a href="#" target="_blank" title="VK">
                        <img src="{% static 'img/vk.png' %}" alt="vk" title="VK">
                    </a>
                    <!-- <a href="#" target="_blank" title="instagram">
                        <img src="img/insgrm.png" alt="instagram" title="instagram">
                    </a> -->
                </div>
            </div>
        </div>
        <div class="ftr-text">
            <div class="indents">
                <p>У нас вы можете заказать суши, роллы, пиццу и другие блюда с доставкой по городу Псков.</p>
                <p>Для вас - только лучшие блюда, приготовленные нашими поварами из свежих продуктов.</p>
                <p>
                    - При заказе от 500 рублей доставка бесплатно!
                    <br>
                    - При заказе от 800 рублей ролл Калифорния в кунжуте в подарок!
                    <br>
                    - При заказе от 1000 рублей ролл Филадельфия тобико маки в подарок!
                    <br>
                    - При заказе от 1800 рублей ролл Филадельфия чиз маки в подарок!
                </p>
            </div>
        </div>
        <p class="about-ip">ИП Виноградов Александр Валерьевич ОГРН313602703200031</p>
    </div>
</footer>

<div class="order-form mfp-hide" id="order-form">
    <div class="form-content">
        <form action="{% url 'catalog:order_path' %}" method="post">
            {% csrf_token %}
            {{ order_form.order_product }}
            <div class="input-box">
                <span class="title">Ваше имя</span>
                {{ order_form.person_name }}
            </div>
            <div class="input-box">
                <span class="title">Ваш телефон</span>
                {{ order_form.person_phone }}
            </div>
            <div class="input-box">
                <span class="title">Сообщение</span>
                {{ order_form.message }}
            </div>
            <input type="submit" name="make-order">
        </form>
    </div>

</div>

<script src="{% static 'js/jquery-1.12.0.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/dropit.js' %}"></script>
<script src="{% static 'js/classie.js' %}"></script>
<script src="{% static 'js/jquery-ui.effects.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.ba-hashchange.min.js' %}"></script>
<script src="{% static 'js/jquery.easytabs.min.js' %}"></script>
<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU"></script>
<script src="{% static 'js/jquery.matchHeight.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/blocks/header.html
<header>
    <div class="large-wrapper clr">
        <a href="/" class="logotype"></a>
        <div class="address-top" style="float: right">
            <div class="address-item">
                <span class="street">Михайловская, 1</span>
                <a href="tel:88112600601" class="phone" title="8 (8112) 600-601">8 (8112) 600-601</a>
            </div>
            <div class="address-item">
                <span class="street">Льва Толстого, 3</span>
                <a href="tel:89118996060" class="phone" title="8-911-899-60-60">8-911-899-60-60</a>
            </div>
        </div>
        <!-- <div class="user-block">
            <a href="auth-popup.html" class="cabinet" title="Личный кабинет"><i class="fa fa-user-circle-o fa-2"></i>Личный кабинет</a>
            <a class="cart" href="cart.html">
                <i class="fa fa-shopping-cart fa-lg"></i>
                <span class="cart-label">Корзина</span>
                <span class="cart-count">10</span>
            </a>
        </div> -->
    </div>
</header>

templates/blocks/main-slider.html
{% load staticfiles %}

<div class="top-slider">
    <div class="action-slider owl-carousel">
        <div class="a-slide">
            <img src="{% static 'images/action1.jpg' %}" alt="Акция 1" title="Акция 1" />
        </div>
        <div class="a-slide">
            <img src="{% static 'images/action1.jpg' %}" alt="Акция 1" title="Акция 1" />
        </div>
        <div class="a-slide">
            <img src="{% static 'images/action1.jpg' %}" alt="Акция 1" title="Акция 1" />
        </div>
    </div>
</div>

templates/blocks/nav.html
{% load staticfiles %}
{% load thumbnail %}
<nav>
    <div class="large-wrapper clr">
        <div class="mob-menu">Меню</div>
        <ul class="nav-menu">
            <li>
                <a href="{% url 'catalog:catalog' %}" title="Меню" class="sub-menu-trigger">Меню</a>
                <ul class="sub-menu-categories clr">
                    {% for Category in full_menu %}
                    <li>
                        <a href="{% url 'catalog:category' pk=Category.pk %}" title="{{Category.ctg_title}}">
                            <img src="{{ Category.ctg_image|thumbnail_url:'preview' }}" alt="{{ Category.ctg_name }}" title="{{ Category.ctg_name }}">
                            <span>{{ Category.ctg_name }}</span>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            <!-- <li><a href="restuarants.html" title="Рестораны">Рестораны</a></li> -->
            <!-- <li><a href="#" title="Акции">Акции</a></li> -->
            <li><a href="{% url 'pages:delivery_page' %}" title="Доставка">Доставка</a></li>
            <!-- <li><a href="news.html" title="Новости">Новости</a></li> -->
            <li><a href="{% url 'pages:contact_page' %}" title="Контакты">Контакты</a></li>
        </ul>
        <!-- <div class="find">
            <form action="#">
                <button type="submit" name="searchButtton"></button>
                <input type="search" name="searchField" placeholder="Поиск...">
            </form>
        </div> -->
    </div>
</nav>

templates/blocks/presents.html
{% load staticfiles %}

<div class="presents-block">
    <div class="large-wrapper">
        <h2>
            <p class="part1">Стань постоянным гостем </p>
            <p class="part2">и получай подарки! </p>
        </h2>
        <form action="#">
            <div class="became-guest clr">
                <div class="person-data clr">
                    <div class="input-box">
                        <div class="input-content">
                            <input type="text" name="person-name">
                            <span class="placeholder">Ваше имя</span>
                        </div>
                    </div>
                    <div class="input-box">
                        <div class="input-content">
                            <input type="text" name="person-surname">
                            <span class="placeholder">Ваша фамилия</span>
                        </div>
                    </div>
                    <div class="input-box">
                        <div class="input-content">
                            <input type="text" name="person-phone">
                            <span class="placeholder">Ваш телефон</span>
                        </div>
                    </div>
                </div>
                <div class="submit-data">
                    <input type="submit" value="Отправить">
                </div>
            </div>
        </form>
    </div>
    <img src="{% static 'images/japanese-home1.png' %}" alt="Стань постоянным гостем и получай подарки!" class="pic-left">
    <img src="{% static 'images/bamboo1.png' %}" alt="Стань постоянным гостем и получай подарки!" class="pic-right">
</div>

templates/catalog/catalog-hits.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load thumbnail %}


{% block content %}
    {% include "blocks/main-slider.html" %}
    <div class="catalog main">
        <div class="small-wrapper">
            <h2>Успей заказать сегодня</h2>
            <div class="catalog-list clr">
                {% for Product in ctlgItems %}
                    <div class="item">
                        <div class="item-content">
                            <a class="image-box" href="{% url 'catalog:product' pk=Product.pk %}" title="{{ Product.prod_name }}">
                                <img src="{{ Product.prod_image|thumbnail_url:'preview' }}" alt="{{Product.prod_name}}" title="{{ Product.prod_name }}">
                            </a>
                            <a class="title-item" href="{% url 'catalog:product' pk=Product.pk %}" title="{{ Product.prod_name }}">{{ Product.prod_name }}</a>
                            <span class="item-components">{{ Product.prod_descr|safe }}</span>
                            <div class="bottom-info clr">
                                <div class="left-col">
                                    <div class="prod-weight">{{ Product.prod_weight }} г.</div>
                                    <div class="prod-price">{{ Product.prod_price }} <span>Р.</span></div>
                                </div>
                                <div class="right-col">
                                    <div class="to-cart-control">
                                        <span class="amount-btn plus"></span>
                                        <span class="amount-text">1</span>
                                        <span class="amount-btn minus"></span>
                                        <a class="cart-btn" href="#order-form"></a>
                                    </div>
                                </div>
                            </div>
                            {% if Product.prod_ishit > 0 %}
                                <div class="item-tag action"></div>
                            {% endif %}
                            {% if Product.prod_isnovelty > 0 %}
                                <div class="item-tag novelty"></div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                <div class="bg-clipart"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/catalog/catalog-list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load thumbnail %}

{% block content %}
    <div class="catalog inner">
        <div class="small-wrapper">
            <h1>Каталог</h1>
            <div class="catalog-list clr">
                {% for Product in ctlgItems %}
                    <div class="item">
                        <div class="item-content">
                            <a class="image-box" href="{% url 'catalog:product' pk=Product.pk %}" title="{{ Product.prod_name }}">
                                <img src="{{ Product.prod_image|thumbnail_url:'preview' }}" alt="{{Product.prod_name}}" title="{{ Product.prod_name }}">
                            </a>
                            <a class="title-item" href="{% url 'catalog:product' pk=Product.pk %}" title="{{ Product.prod_name }}">{{ Product.prod_name }}</a>
                            <span class="item-components">{{ Product.prod_descr|safe }}</span>
                            <div class="bottom-info clr">
                                <div class="left-col">
                                    <div class="prod-weight">{{ Product.prod_weight }} г.</div>
                                    <div class="prod-price">{{ Product.prod_price }} <span>Р.</span></div>
                                </div>
                                <div class="right-col">
                                    <div class="to-cart-control">
                                        <span class="amount-btn plus"></span>
                                        <span class="amount-text">1</span>
                                        <span class="amount-btn minus"></span>
                                        <span class="cart-btn"></span>
                                    </div>
                                </div>
                            </div>
                            {% if Product.prod_ishit > 0 %}
                                <div class="item-tag action"></div>
                            {% endif %}
                            {% if Product.prod_isnovelty > 0 %}
                                <div class="item-tag novelty"></div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                <div class="bg-clipart"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/catalog/full-menu.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load thumbnail %}


{% block content %}
    <div class="catalog inner">
        <div class="small-wrapper">
            <h1>Меню</h1>
            <div class="catalog-list menu-list clr">
                {% for Category in full_menu %}
                    <div class="item">
                        <div class="item-content">
                            <a class="image-box" href="{% url 'catalog:category' pk=Category.pk %}">
                                <img src="{{ Category.ctg_image|thumbnail_url:'preview' }}" alt="{{ Category.ctg_name }}" title="{{ Category.ctg_name }}">
                            </a>
                            <a class="title-item" href="{% url 'catalog:category' pk=Category.pk %}" title="{{ Category.ctg_name }}">{{ Category.ctg_name }}</a>
                        </div>
                    </div>
                {% endfor %}
                <div class="bg-clipart"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/catalog/product-detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load thumbnail %}

{% block content %}
	<div class="product-detail">
		<div class="large-wrapper">
			<div class="product-header">
				<h1>{{ prodInfo.prod_name }}</h1>
			</div>
			<div class="prod-cols clr">
				<div class="col">
					<div class="content">
						<div class="image-box">
							<div class="product-slider owl-carousel">
								<img src="{{ prodInfo.prod_image|thumbnail_url:'big_preview' }}" alt="{{ prodInfo.prod_name }}" title="{{ prodInfo.prod_name }}">
							</div>
						</div>
					</div>
				</div>
				<div class="col">
					<div class="content">
						<p class="subtitle">Описание:</p>
						<span class="item-components">{{ prodInfo.prod_descr|safe }}</span>
						<div class="bottom-info clr">
							<div class="left-col">
								<div class="prod-weight">
									<span class="subtitle">Вес: </span>
									{{ prodInfo.prod_weight }}
								</div>
								<div class="prod-price">
									<span class="subtitle">Цена: </span>
									{{ prodInfo.prod_price }} <span>Р.</span>
								</div>
							</div>
							<div class="right-col">
								<div class="to-cart-control">
									<span class="amount-btn plus"></span>
									<span class="amount-text">1</span>
									<span class="amount-btn minus"></span>
									<span class="cart-btn"></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/catalog/product-popup.html
 {% extends 'base.html' %}

{% load staticfiles %}
{% load thumbnail %}

 {% block content %}
    <div class="product-modal">
        <div class="image-box">
            <img src="images/philadelphia-big.jpg" alt="philadelphia">
        </div>
        <span class="title-item" data-modal>Филадельфия люкс</span>
        <span class="item-components">Рис Японский, лосось филе, сыр сливочный, водоросли Нори.</span>
        <div class="bottom-info clr">
            <div class="left-col">
                <div class="prod-weight">200 гр.</div>
                <div class="prod-price">325 <span>Р.</span></div>
            </div>
            <div class="right-col">
                <div class="to-cart-control">
                    <span class="amount-btn plus"></span>
                    <span class="amount-text">1</span>
                    <span class="amount-btn minus"></span>
                    <span class="cart-btn"></span>
                </div>
            </div>
        </div>
        <a href="product-detail.html" target="_blank" class="gotoDetali">Перейти в карточку товара</a>
        <button title="Close (Esc)" type="button" class="mfp-close">×</button>
    </div>
{% endblock %}

templates/pages/contacts.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="page-title">
	    <div class="large-wrapper">
	        <h1>Контакты</h1>
	    </div>
	</div>

	<div class="large-wrapper">
		<div class="resuarants clr">
			<div class="col">
				<div class="content">
					<div class="rest-head">
						<h2>Ресторан «Окинава» на ул. Михайловская, 1</h2>
					</div>
	                <div class="rest-contacts">
	                    <div class="cont-item phone">
	                        <a href="+78112600601">8 (8112) 600-601</a>
	                        <a href="+79118896060">8-911-889-60-60</a>
	                    </div>
	                    <div class="cont-item time">
	                        <span>Заказ столиков:</span>
	                        <a href="tel:+78112600601">8 (8112) 600-601</a>
	                    </div>
	                    <div class="cont-item time">
	                        <span>Ежедневно:</span>
	                        <span>11:00 - 23:00, пт-сб: до 1:00</span>
	                    </div>
	                </div>
					<!-- <div class="big-photo">
						<a href="images/rest1.jpg">
							<img src="images/rest1.jpg" alt="Окинава">
						</a>
					</div> -->
				</div>
			</div>
			<div class="col">
				<div class="content">
					<div class="rest-head">
						<h2>Ресторан «Окинава» на ул. Льва Толстого, 3</h2>
					</div>
	                <div class="rest-contacts">
	                    <div class="cont-item phone">
	                        <a href="tel:+79118996060">8-911-899-60-60</a>
	                        <a href="tel:+78112201060">8 (8112) 20-10-60</a>
	                    </div>
	                    <div class="cont-item time">
	                        <span>Заказ столиков:</span>
	                        <a href="tel:+79118996060">8-911-899-60-60</a>
	                    </div>
	                    <div class="cont-item time">
	                        <span>Ежедневно:</span>
	                        <span> 10:00 - 23:00 </span>
	                    </div>
	                </div>
					<!-- <div class="big-photo">
						<a href="images/rest1.jpg">
							<img src="images/rest1.jpg" alt="Окинава">
						</a>
					</div> -->
				</div>
			</div>
		</div>
	</div>

	<div class="map" id="map"></div>

	<script type="text/javascript">
		ymaps.ready(function () {
		var myMap = new ymaps.Map('map', {
				center: [57.8139,28.3489],
				zoom: 17,
				controls: []
			}),
			myPlacemark = new ymaps.Placemark(myMap.getCenter(), {
				hintContent: 'Окинава',
				balloonContent: 'Окинава'
			}, {
				iconLayout: 'default#image',
				iconImageHref: 'img/location-pin.png',
				iconImageSize: [64, 64],
				iconImageOffset: [-3, -42]
			}),
			zoomControl;
			zoomControl = new ymaps.control.ZoomControl({
				options:{
					position:{top: 50, right: 10}
				}
			});
			myMap.behaviors.disable('scrollZoom');
			myMap.geoObjects.add(myPlacemark);
			myMap.controls.add(zoomControl);
		});
	</script>
{% endblock %}

templates/pages/delivery.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="page-title">
	    <div class="large-wrapper">
	        <h1>Доставка</h1>
	    </div>
	</div>

	<div class="delivery">
	    <div class="large-wrapper">
	        <div class="deliv-head">
	            <p class="intro">
	                Не хочется выбираться из дома,<br>или неожиданно нагрянули гости?
	            </p>
	            <p class="text">
	                Просто выберите понравившееся блюдо и закажите!
	            </p>
	        </div>
	        <div class="deliv-order">
	            <a href="{% url 'catalog:catalog' %}">Заказать</a>
	        </div>
	        <div class="deliv-phones">
	            <span>Телефоны доставки:</span>
	            <a href="tel:+78112600601">8 (8112) 600-601</a>
	            <a href="tel:+79118996060">8-911-899-60-60</a>
	        </div>
	    </div>
	    <img src="{% static 'images/sakura1.png' %}" alt="Доставка" class="left-sakura">
	    <img src="{% static 'images/sakura2.png' %}" alt="Доставка" class="right-sakura">
	</div>

	<div class="advantages">
	    <div class="large-wrapper">
	        <div class="advs-list clr">
	            <div class="item">
	                <div class="item-content">
	                    <img src="{% static 'images/plate.png' %}" alt="Только свежая еда" style="padding-top:40px;">
	                    <div class="adv-text">Только свежая еда</div>
	                </div>
	            </div>
	            <div class="item">
	                <div class="item-content">
	                    <img src="{% static 'images/money.png' %}" alt="Минимальный заказ от 500 рублей">
	                    <div class="adv-text">Минимальный заказ от <br> 500 рублей</div>
	                </div>
	            </div>
	            <div class="item">
	                <div class="item-content">
	                    <img src="{% static 'images/cards.png' %}" alt="Любые способы оплаты" style="padding-top:40px;">
	                    <div class="adv-text">Любые способы оплаты</div>
	                </div>
	            </div>
	            <div class="item">
	                <div class="item-content">
	                    <img src="{% static 'images/free-delivery.png' %}" alt="Бесплатная доставка">
	                    <div class="adv-text">Бесплатная доставка</div>
	                </div>
	            </div>
	            <div class="item">
	                <div class="item-content">
	                    <img src="{% static 'images/clock.png' %}" alt="Своевременная доставка">
	                    <div class="adv-text">Своевременная доставка</div>
	                </div>
	            </div>
	            <div class="item">
	                <div class="item-content">
	                    <img src="{% static 'images/bonuses.png' %}" alt="Постоянные бонусы">
	                    <div class="adv-text">Постоянные бонусы</div>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
{% endblock %}